version: 2
jobs:
  node:
    working_directory: ~/rn-dp
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "example/yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "example/package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "example/yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "example/package.json" }}-{{ arch }}
          paths:
            - example/node_modules

  android:
    working_directory: ~/rn-dp/example/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/rn-dp/example/

      - attach_workspace:
          at: ~/rn-dp/example/

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane tests
          command: |
            mkdir -p test-results/fastlane
            bundle exec fastlane test
            mv fastlane/report.xml test-results/fastlane
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  version: 2
  node-android:
    jobs:
      - node
      - android:
          requires:
            - node