version: 2
jobs:
  node:
    working_directory: ~/rn-dp
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "example/yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "example/package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "example/yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "example/package.json" }}-{{ arch }}
          paths:
            - example/node_modules

  android:
    working_directory: ~/rn-dp/example/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/rn-dp

      - attach_workspace:
          at: ~/rn-dp

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

workflows:
  version: 2
  node-android:
    jobs:
      - node
      - android:
          requires:
            - node